apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
    - name: goserver-service
      protocol: TCP
      port: 8080 # porta de acesso ao serviço
      targetPort: 8080 # porta de acesso a aplicação